monolog:
    channels:
        - controller # Channel pour les loggers des controllers
        - security # Channel pour les loggers des services d'authentifications, de gestion des rôles
        - service # Channel pour les loggers des services d'une manière générale
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!event", "!doctrine"]
            # uncomment to get logging in your browser
            # you may have to allow bigger header sizes in your Web server configuration
            #firephp:
            #    type: firephp
            #    level: info
            #chromephp:
            #    type: chromephp
            #    level: info
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event", "!doctrine"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
            test:
                type: test
                level: debug
                process_psr_3_messages: false
                channels: [ "!event", "!doctrine" ]

when@prod:
    monolog:
        handlers:
            main:
                type: rotating_file
                max_files: 10
                path: "%env(resolve:LOG_DIR)%/%kernel.environment%.log"
                level: debug
                channels: [ "!event", "!deprecation" ]
            controller:
                type: rotating_file
                max_files: 10
                path: "%env(resolve:LOG_DIR)%/controller.log"
                level: info
                channels: [ "controller" ]
            security:
                type: rotating_file
                max_files: 10
                path: "%env(resolve:LOG_DIR)%/security.log"
                level: info
                channels: [ "security" ]
            service:
                type: rotating_file
                max_files: 10
                path: "%env(resolve:LOG_DIR)%/service.log"
                level: info
                channels: [ "service" ]
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
