nelmio_api_doc:
    documentation:
        info:
            title: Basejump Symfony
            description:
            version: 0.1.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/swagger.*$) # Accepts routes under /api except /api/doc
