version: '3'
services:
  php-fpm:
    image: php-basejump
    build:
      context: ./
      dockerfile: ./docker/Dockerfile-php
    restart: unless-stopped
    user: "${DUID:-0}:${DGID:-0}"
    volumes:
      - ./:/var/www/html
      - ~/.cache:/.cache
      - ~/.config:/.config
      - ~/.composer:/.composer
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      PHP_CS_FIXER_IGNORE_ENV: 1
      XDEBUG_MODE: "debug"
      XDEBUG_CONFIG: >-
        idekey=PHPSTORM
        log_level=0
        client_host=host.docker.internal
      PHP_IDE_CONFIG: serverName=basejump-docker
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./:/var/www/html:ro
      - ./docker/symfony_vhost.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 7180:80
  db:
    image: postgres:12.3
    restart: unless-stopped
    container_name: basejump_postgre
    environment:
      POSTGRES_DB: basejump
      POSTGRES_USER: basejump
      POSTGRES_PASSWORD: basejump
      PGDATA: /var/lib/postgresql/data
    ports:
      - 7183:5432
    volumes:
      - postgresql_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:4.23
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: basejump
      PGADMIN_DEFAULT_PASSWORD: basejump
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 7181:80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
  maildev:
    image: djfarrelly/maildev
    restart: unless-stopped
    container_name: basejump_maildev
    ports:
      - 7182:80

volumes:
  postgresql_data:
  pgadmin_data:
