app.swagger:
    path: /api/swagger.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }

app.swagger_ui:
    path: /api/swagger
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
